language: python

python: 
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-flake8
  - pip install coveralls

script:
  - flake8 --ignore=W391
  - python -m unittest discover
  - pytest --cov=test/

after_success:
  - coveralls
