language: python

python: 
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - python -m unittest discover
  - pytest --cov=test_prime_function

after_success:
  - coveralls
