language: python

python: 
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

before install:
  - cd test

script:
  - python -m unittest discover test
  - pytest --cov=test_prime_function

after_success:
  - coveralls
