# This workflow will install Python dependencies, run unit tests, lint & provide coverage with a variety of Python versions

name: Python Lint, Test & Coverage

on:
  push:
  pull_request:
    types:
      - opened

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 
        python -m pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # ignore Warning 391, Blank line at end of file
        flake8 . --ignore=W391, 
    - name: Run unittest with code coverage
      run: |
        coverage run -m unittest discover
    - name: Show coverage report
      run: |
        coverage report -m
